export const MOCK_TENANT = {
  id: "tnt_01h9xk2p3q4r5s6t7u8v",
  name: "Acme Corp",
  slug: "acme-corp",
  status: "active" as const,
  plan: "growth" as const,
  region: "us-east-1",
  mfa_policy: "required-admins" as const,
  stripe_customer_id: "cus_Nk2pXr8Tz",
  stripe_subscription_id: "sub_Nk2pXr8TzGrowth",
  created_at: "2024-08-15T10:00:00Z",
  created_by: "sarah@acme.com",
};

export const MOCK_WORKSPACES = [
  {
    id: "wsp_01h9prod2p3q4r5s6t7u8",
    name: "Production",
    mode: "isolated-realm" as const,
    status: "active" as const,
    is_default: true,
    tenant_id: MOCK_TENANT.id,
    keycloak: {
      realm: "tnt_01h9xk2p3q4r5s6t7u8v",
      issuer: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v",
      jwks_uri: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/certs",
      well_known: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/.well-known/openid-configuration",
    },
    created_at: "2024-08-15T10:00:00Z",
    created_by: "sarah@acme.com",
    mau: 8340,
    app_count: 2,
    admin_count: 3,
  },
  {
    id: "wsp_01h9stag2p3q4r5s6t7u9",
    name: "Staging",
    mode: "shared-realm" as const,
    status: "active" as const,
    is_default: false,
    tenant_id: MOCK_TENANT.id,
    keycloak: {
      realm: "wsp_01h9stag2p3q4r5s6t7u9",
      issuer: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9",
      jwks_uri: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9/protocol/openid-connect/certs",
      well_known: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9/.well-known/openid-configuration",
    },
    created_at: "2024-09-03T14:20:00Z",
    created_by: "sarah@acme.com",
    mau: 127,
    app_count: 1,
    admin_count: 2,
  },
];

export const MOCK_APPS = [
  {
    id: "app_01h9dash2p3q4r5s6t7u8",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    name: "Acme Dashboard",
    status: "active" as const,
    type: "public" as const,
    pkce: "required" as const,
    scopes: ["openid", "profile", "email"],
    redirect_uris: ["https://app.acme.com/auth/callback", "https://app.acme.com/silent-renew"],
    post_logout_redirect_uris: ["https://app.acme.com/logged-out"],
    web_origins: ["https://app.acme.com"],
    access_token_seconds: 900,
    refresh_token_seconds: 2592000,
    oidc: {
      client_id: "app_01h9dash2p3q4r5s6t7u8",
      issuer: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v",
      authorization_endpoint: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/auth",
      token_endpoint: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/token",
      jwks_uri: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/certs",
    },
    created_at: "2024-08-16T09:30:00Z",
    created_by: "sarah@acme.com",
    last_login_at: "2024-11-01T14:22:00Z",
    logins_30d: 14820,
    active_sessions: 312,
  },
  {
    id: "app_01h9api2p3q4r5s6t7u9x",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    name: "Backend API",
    status: "error" as const,
    error_reason: "JWKS endpoint returning HTTP 503. Token validation is failing for all new authentication requests.",
    error_since: "2024-11-01T03:45:00Z",
    type: "confidential" as const,
    pkce: "optional" as const,
    scopes: ["openid", "profile", "email", "offline_access"],
    redirect_uris: ["https://api.acme.com/auth/callback"],
    post_logout_redirect_uris: [],
    web_origins: [],
    access_token_seconds: 3600,
    refresh_token_seconds: 7776000,
    oidc: {
      client_id: "app_01h9api2p3q4r5s6t7u9x",
      issuer: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v",
      authorization_endpoint: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/auth",
      token_endpoint: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/token",
      jwks_uri: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/openid-connect/certs",
    },
    created_at: "2024-08-16T11:00:00Z",
    created_by: "sarah@acme.com",
    last_login_at: "2024-11-01T03:12:00Z",
    logins_30d: 6342,
    active_sessions: 88,
  },
  {
    id: "app_01h9mob2p3q4r5s6t7u0z",
    workspace_id: "wsp_01h9stag2p3q4r5s6t7u9",
    workspace_name: "Staging",
    name: "Mobile App (Staging)",
    status: "provisioning" as const,
    type: "public" as const,
    pkce: "required" as const,
    scopes: ["openid", "profile", "email"],
    redirect_uris: ["acme://auth/callback", "https://staging.acme.com/auth/callback"],
    post_logout_redirect_uris: ["acme://auth/logout"],
    web_origins: [],
    access_token_seconds: 900,
    refresh_token_seconds: 2592000,
    oidc: {
      client_id: "app_01h9mob2p3q4r5s6t7u0z",
      issuer: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9",
      authorization_endpoint: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9/protocol/openid-connect/auth",
      token_endpoint: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9/protocol/openid-connect/token",
      jwks_uri: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9/protocol/openid-connect/certs",
    },
    created_at: "2024-09-04T08:15:00Z",
    created_by: "james@acme.com",
    last_login_at: null as string | null,
    logins_30d: 243,
    active_sessions: 12,
  },
];

export const MOCK_ADMINS = [
  {
    id: "adm_01h9own2p3q4r5s6t7u8v",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    email: "sarah@acme.com",
    full_name: "Sarah Chen",
    role: "owner" as const,
    status: "active" as const,
    created_at: "2024-08-15T10:00:00Z",
    invited_by: null as string | null,
    invite_expires_at: null as string | null,
  },
  {
    id: "adm_01h9adm2p3q4r5s6t7u9w",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    email: "james@acme.com",
    full_name: "James Park",
    role: "admin" as const,
    status: "active" as const,
    created_at: "2024-08-20T14:30:00Z",
    invited_by: "sarah@acme.com",
    invite_expires_at: null as string | null,
  },
  {
    id: "adm_01h9bil2p3q4r5s6t7u0x",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    email: "finance@acme.com",
    full_name: "Finance Team",
    role: "billing" as const,
    status: "active" as const,
    created_at: "2024-09-01T09:00:00Z",
    invited_by: "sarah@acme.com",
    invite_expires_at: null as string | null,
  },
  {
    id: "adm_01h9inv2p3q4r5s6t7u1y",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    email: "new.dev@acme.com",
    full_name: "Alex Rivera",
    role: "viewer" as const,
    status: "invited" as const,
    created_at: "2024-10-28T16:45:00Z",
    invited_by: "sarah@acme.com",
    invite_expires_at: "2024-11-04T16:45:00Z",
  },
];

export const MOCK_AUDIT_LOGS = [
  { id: 8, action: "support.access-enabled", resource_type: "workspace", resource_id: "wsp_01h9prod2p3q4r5s6t7u8", actor_email: "james@acme.com", new_state: null, previous_state: null, created_at: "2024-10-15T10:05:00Z", ip_address: "72.38.91.114", source_screen: "portal/settings", severity: "high" as const },
  { id: 6, action: "admin.invited", resource_type: "admin", resource_id: "adm_01h9inv2p3q4r5s6t7u1y", actor_email: "sarah@acme.com", new_state: "invited", previous_state: null, created_at: "2024-10-28T16:45:00Z", ip_address: "104.21.8.42", source_screen: "portal/team", severity: "info" as const },
  { id: 4, action: "tenant.updated", resource_type: "tenant", resource_id: "tnt_01h9xk2p3q4r5s6t7u8v", actor_email: "sarah@acme.com", new_state: "active", previous_state: "active", created_at: "2024-10-01T08:00:00Z", ip_address: "104.21.8.42", source_screen: "portal/settings", severity: "info" as const },
  { id: 3, action: "app.secret-rotated", resource_type: "app", resource_id: "app_01h9api2p3q4r5s6t7u9x", actor_email: "james@acme.com", new_state: null, previous_state: null, created_at: "2024-09-12T11:22:00Z", ip_address: "72.38.91.114", source_screen: "portal/apps/detail", severity: "medium" as const },
  { id: 7, action: "app.created", resource_type: "app", resource_id: "app_01h9mob2p3q4r5s6t7u0z", actor_email: "james@acme.com", new_state: "active", previous_state: null, created_at: "2024-09-04T08:15:00Z", ip_address: "72.38.91.114", source_screen: "portal/apps/new", severity: "info" as const },
  { id: 5, action: "workspace.created", resource_type: "workspace", resource_id: "wsp_01h9stag2p3q4r5s6t7u9", actor_email: "sarah@acme.com", new_state: "active", previous_state: null, created_at: "2024-09-03T14:20:00Z", ip_address: "104.21.8.42", source_screen: "portal/workspaces/new", severity: "info" as const },
  { id: 2, action: "admin.invited", resource_type: "admin", resource_id: "adm_01h9adm2p3q4r5s6t7u9w", actor_email: "sarah@acme.com", new_state: "invited", previous_state: null, created_at: "2024-08-20T14:30:00Z", ip_address: "104.21.8.42", source_screen: "portal/team", severity: "info" as const },
  { id: 1, action: "app.created", resource_type: "app", resource_id: "app_01h9dash2p3q4r5s6t7u8", actor_email: "sarah@acme.com", new_state: "active", previous_state: null, created_at: "2024-08-16T09:30:00Z", ip_address: "104.21.8.42", source_screen: "portal/apps/new", severity: "info" as const },
  { id: 9, action: "saml.sp-registered", resource_type: "saml_sp", resource_id: "ssp_01h9sf_prod_2p3q4r", actor_email: "sarah@acme.com", new_state: "active", previous_state: null, created_at: "2024-09-01T10:00:00Z", ip_address: "104.21.8.42", source_screen: "portal/saml/new", severity: "info" as const },
  { id: 10, action: "saml.sp-registered", resource_type: "saml_sp", resource_id: "ssp_01h9gw_prod_3q4r5s", actor_email: "james@acme.com", new_state: "active", previous_state: null, created_at: "2024-10-05T14:30:00Z", ip_address: "72.38.91.114", source_screen: "portal/saml/new", severity: "info" as const },
  { id: 11, action: "saml.sp-disabled", resource_type: "saml_sp", resource_id: "ssp_01h9az_stag_4r5s6t", actor_email: "james@acme.com", new_state: "disabled", previous_state: "active", created_at: "2024-10-22T09:15:00Z", ip_address: "72.38.91.114", source_screen: "portal/saml/detail", severity: "medium" as const },
];

export const MOCK_USAGE = {
  mau: 8467,
  mau_limit: 50000,
  mau_pct: 17,
  logins_30d: 21405,
  token_refreshes_30d: 187320,
  monthly_trend: [
    { month: "May", mau: 5120 }, { month: "Jun", mau: 5890 }, { month: "Jul", mau: 6740 },
    { month: "Aug", mau: 7210 }, { month: "Sep", mau: 7880 }, { month: "Oct", mau: 8467 },
  ],
};

export const MOCK_SAML_SPS = [
  {
    id: "ssp_01h9sf_prod_2p3q4r",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    name: "Salesforce Production",
    entity_id: "https://customer.my.salesforce.com",
    acs_url: "https://customer.my.salesforce.com/services/saml2/acs",
    slo_url: "https://customer.my.salesforce.com/services/saml2/slo" as string | null,
    name_id_format: "email" as const,
    sign_assertions: true,
    encrypt_assertions: false,
    status: "active" as const,
    last_sso_at: "2024-11-01T11:34:00Z" as string | null,
    sso_count_30d: 4821,
    created_at: "2024-09-01T10:00:00Z",
    created_by: "sarah@acme.com",
    idp_metadata_url: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/saml/descriptor",
    attribute_mappings: [
      { keycloak_attribute: "email", saml_attribute_name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", saml_attribute_format: "URI" as const, required: true },
      { keycloak_attribute: "firstName", saml_attribute_name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", saml_attribute_format: "URI" as const, required: false },
      { keycloak_attribute: "lastName", saml_attribute_name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", saml_attribute_format: "URI" as const, required: false },
      { keycloak_attribute: "realm_roles", saml_attribute_name: "groups", saml_attribute_format: "Basic" as const, required: false },
    ],
  },
  {
    id: "ssp_01h9gw_prod_3q4r5s",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    name: "Google Workspace SSO",
    entity_id: "https://accounts.google.com/o/saml2?idpid=C02abc123",
    acs_url: "https://accounts.google.com/o/saml2/acs?idpid=C02abc123",
    slo_url: null as string | null,
    name_id_format: "email" as const,
    sign_assertions: true,
    encrypt_assertions: false,
    status: "active" as const,
    last_sso_at: "2024-11-01T09:22:00Z" as string | null,
    sso_count_30d: 1247,
    created_at: "2024-10-05T14:30:00Z",
    created_by: "james@acme.com",
    idp_metadata_url: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/protocol/saml/descriptor",
    attribute_mappings: [
      { keycloak_attribute: "email", saml_attribute_name: "email", saml_attribute_format: "Basic" as const, required: true },
      { keycloak_attribute: "firstName", saml_attribute_name: "firstName", saml_attribute_format: "Basic" as const, required: false },
    ],
  },
  {
    id: "ssp_01h9az_stag_4r5s6t",
    workspace_id: "wsp_01h9stag2p3q4r5s6t7u9",
    workspace_name: "Staging",
    name: "Azure AD (Staging Test)",
    entity_id: "https://login.microsoftonline.com/acme-tenant-id/saml2",
    acs_url: "https://login.microsoftonline.com/acme-tenant-id/saml2/acs",
    slo_url: "https://login.microsoftonline.com/acme-tenant-id/saml2/slo" as string | null,
    name_id_format: "persistent" as const,
    sign_assertions: true,
    encrypt_assertions: false,
    status: "disabled" as const,
    last_sso_at: null as string | null,
    sso_count_30d: 0,
    created_at: "2024-10-20T08:00:00Z",
    created_by: "james@acme.com",
    idp_metadata_url: "https://id.foundry-iam.dev/realms/wsp_01h9stag2p3q4r5s6t7u9/protocol/saml/descriptor",
    attribute_mappings: [
      { keycloak_attribute: "email", saml_attribute_name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", saml_attribute_format: "URI" as const, required: true },
      { keycloak_attribute: "realm_roles", saml_attribute_name: "groups", saml_attribute_format: "Basic" as const, required: false },
    ],
  },
];

export const MOCK_SCIM_CONFIGS = [
  {
    id: "scimcfg_01h9prod01",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    enabled: true,
    token_prefix: "scim_live",
    base_url: "https://api.foundry-iam.dev/scim/v2/wsp_01h9prod2p3q4r5s6t7u8",
    allowed_operations: ["CREATE", "UPDATE", "DISABLE"] as string[],
    sync_groups: true,
    deprovision_action: "disable" as const,
    last_sync_at: "2024-11-01T11:45:00Z" as string | null,
    sync_error_count: 2,
    idp_hint: "Okta",
    created_at: "2024-09-15T10:00:00Z",
    created_by: "sarah@acme.com",
  },
  {
    id: "scimcfg_01h9stag02",
    workspace_id: "wsp_01h9stag2p3q4r5s6t7u9",
    workspace_name: "Staging",
    enabled: false,
    token_prefix: "",
    base_url: "https://api.foundry-iam.dev/scim/v2/wsp_01h9stag2p3q4r5s6t7u9",
    allowed_operations: ["CREATE", "UPDATE", "DISABLE", "DELETE"] as string[],
    sync_groups: true,
    deprovision_action: "disable" as const,
    last_sync_at: null as string | null,
    sync_error_count: 0,
    idp_hint: "",
    created_at: "2024-09-03T14:20:00Z",
    created_by: "sarah@acme.com",
  },
];

export const MOCK_SCIM_USERS = [
  {
    id: "scusr_01h9a1b2c3d4",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    keycloak_user_id: "kc-uuid-001",
    external_id: "okta-user-00Abc123",
    username: "john.smith@acme.com",
    display_name: "John Smith",
    active: true,
    last_synced_at: "2024-11-01T11:45:00Z",
    created_at: "2024-09-16T08:00:00Z",
    groups: ["Engineering", "SAML-Salesforce"],
  },
  {
    id: "scusr_01h9b2c3d4e5",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    keycloak_user_id: "kc-uuid-002",
    external_id: "okta-user-00Bcd234",
    username: "maria.gonzalez@acme.com",
    display_name: "Maria Gonzalez",
    active: true,
    last_synced_at: "2024-11-01T11:45:00Z",
    created_at: "2024-09-16T08:00:00Z",
    groups: ["Engineering", "DevOps"],
  },
  {
    id: "scusr_01h9c3d4e5f6",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    keycloak_user_id: "kc-uuid-003",
    external_id: "okta-user-00Cde345",
    username: "alex.kim@acme.com",
    display_name: "Alex Kim",
    active: false,
    last_synced_at: "2024-10-28T14:20:00Z",
    created_at: "2024-09-20T10:30:00Z",
    groups: ["Marketing"],
  },
  {
    id: "scusr_01h9d4e5f6g7",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    keycloak_user_id: "kc-uuid-004",
    external_id: "okta-user-00Def456",
    username: "priya.patel@acme.com",
    display_name: "Priya Patel",
    active: true,
    last_synced_at: "2024-11-01T11:45:00Z",
    created_at: "2024-10-01T09:00:00Z",
    groups: ["Engineering", "Security"],
  },
  {
    id: "scusr_01h9e5f6g7h8",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    keycloak_user_id: "kc-uuid-005",
    external_id: "okta-user-00Efg567",
    username: "ryan.oconnor@acme.com",
    display_name: "Ryan O'Connor",
    active: true,
    last_synced_at: "2024-11-01T11:45:00Z",
    created_at: "2024-10-15T14:00:00Z",
    groups: ["Finance"],
  },
];

export const MOCK_SCIM_LOGS = [
  {
    id: "sclog_01h9l01",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "CREATE" as const,
    resource_type: "User",
    resource_display: "ryan.oconnor@acme.com",
    status: "error" as const,
    error_detail: "userName already exists in realm. Duplicate provisioning attempt from Okta.",
    http_status: 409,
    created_at: "2024-11-01T11:45:12Z",
    external_id: "okta-user-00Efg567",
  },
  {
    id: "sclog_01h9l02",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "UPDATE" as const,
    resource_type: "User",
    resource_display: "john.smith@acme.com",
    status: "error" as const,
    error_detail: "Keycloak realm timeout — user attribute update failed after 3 retries.",
    http_status: 503,
    created_at: "2024-11-01T10:22:08Z",
    external_id: "okta-user-00Abc123",
  },
  {
    id: "sclog_01h9l03",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "DISABLE" as const,
    resource_type: "User",
    resource_display: "alex.kim@acme.com",
    status: "success" as const,
    error_detail: null as string | null,
    http_status: 200,
    created_at: "2024-10-28T14:20:35Z",
    external_id: "okta-user-00Cde345",
  },
  {
    id: "sclog_01h9l04",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "CREATE" as const,
    resource_type: "User",
    resource_display: "ryan.oconnor@acme.com",
    status: "success" as const,
    error_detail: null as string | null,
    http_status: 201,
    created_at: "2024-10-15T14:00:22Z",
    external_id: "okta-user-00Efg567",
  },
  {
    id: "sclog_01h9l05",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "CREATE" as const,
    resource_type: "User",
    resource_display: "priya.patel@acme.com",
    status: "success" as const,
    error_detail: null as string | null,
    http_status: 201,
    created_at: "2024-10-01T09:00:18Z",
    external_id: "okta-user-00Def456",
  },
  {
    id: "sclog_01h9l06",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "UPDATE_GROUP" as const,
    resource_type: "Group",
    resource_display: "Engineering",
    status: "success" as const,
    error_detail: null as string | null,
    http_status: 200,
    created_at: "2024-10-01T09:01:05Z",
    external_id: "okta-group-Eng001",
  },
  {
    id: "sclog_01h9l07",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "CREATE" as const,
    resource_type: "User",
    resource_display: "maria.gonzalez@acme.com",
    status: "success" as const,
    error_detail: null as string | null,
    http_status: 201,
    created_at: "2024-09-16T08:00:45Z",
    external_id: "okta-user-00Bcd234",
  },
  {
    id: "sclog_01h9l08",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    operation: "CREATE" as const,
    resource_type: "User",
    resource_display: "john.smith@acme.com",
    status: "success" as const,
    error_detail: null as string | null,
    http_status: 201,
    created_at: "2024-09-16T08:00:10Z",
    external_id: "okta-user-00Abc123",
  },
];

export const MOCK_IDENTITY_PROVIDERS = [
  {
    id: "idp_01h9okta2p3q4r5s6t7u8",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    alias: "acme-okta",
    display_name: "Sign in with Acme Corp",
    type: "okta" as const,
    enabled: true,
    hide_on_login_page: false,
    domain_hints: ["acme.com", "acme-corp.com"],
    sync_mode: "inherit" as const,
    callback_url: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/broker/acme-okta/endpoint",
    attribute_mappers: [
      { id: "map_email", upstream_claim: "email", user_attribute: "email", sync_mode: "inherit" },
      { id: "map_firstname", upstream_claim: "given_name", user_attribute: "firstName", sync_mode: "inherit" },
      { id: "map_lastname", upstream_claim: "family_name", user_attribute: "lastName", sync_mode: "inherit" },
    ],
    login_count_30d: 1247,
    last_login_at: "2024-11-01T14:22:00Z" as string | null,
    created_at: "2024-09-01T09:00:00Z",
    created_by: "sarah@acme.com",
  },
  {
    id: "idp_01h9azur2p3q4r5s6t7u9",
    workspace_id: "wsp_01h9prod2p3q4r5s6t7u8",
    workspace_name: "Production",
    alias: "acme-azure",
    display_name: "Sign in with Azure AD",
    type: "azure" as const,
    enabled: false,
    hide_on_login_page: false,
    domain_hints: ["acme-eu.com"],
    sync_mode: "force" as const,
    callback_url: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/broker/acme-azure/endpoint",
    attribute_mappers: [
      { id: "map_email_az", upstream_claim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", user_attribute: "email", sync_mode: "inherit" },
      { id: "map_fn_az", upstream_claim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", user_attribute: "firstName", sync_mode: "inherit" },
      { id: "map_ln_az", upstream_claim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", user_attribute: "lastName", sync_mode: "inherit" },
    ],
    login_count_30d: 0,
    last_login_at: null as string | null,
    created_at: "2024-10-15T11:30:00Z",
    created_by: "sarah@acme.com",
  },
  {
    id: "idp_01h9goog2p3q4r5s6t7u0",
    workspace_id: "wsp_01h9stag2p3q4r5s6t7u9",
    workspace_name: "Staging",
    alias: "google",
    display_name: "Sign in with Google",
    type: "google" as const,
    enabled: true,
    hide_on_login_page: false,
    domain_hints: [] as string[],
    sync_mode: "inherit" as const,
    callback_url: "https://id.foundry-iam.dev/realms/tnt_01h9xk2p3q4r5s6t7u8v/broker/google/endpoint",
    attribute_mappers: [
      { id: "map_email_g", upstream_claim: "email", user_attribute: "email", sync_mode: "inherit" },
      { id: "map_fn_g", upstream_claim: "given_name", user_attribute: "firstName", sync_mode: "inherit" },
    ],
    login_count_30d: 89,
    last_login_at: "2024-11-01T10:15:00Z" as string | null,
    created_at: "2024-09-15T14:00:00Z",
    created_by: "sarah@acme.com",
  },
];

export const MOCK_PLANS = [
  {
    id: "starter", name: "Starter", monthly_fee: 99, mau_included: 10000,
    overage_rate: 0.012, workspaces: 1, sla: "99.5%",
    features: ["1 workspace", "10K MAU included", "PKCE + OIDC", "Email support", "Audit logs (30 days)"],
  },
  {
    id: "growth", name: "Growth", monthly_fee: 399, mau_included: 50000,
    overage_rate: 0.010, workspaces: 3, sla: "99.9%",
    features: ["3 workspaces", "50K MAU included", "All Starter features", "MFA policies", "Priority support", "Audit logs (1 year)"],
  },
  {
    id: "enterprise", name: "Enterprise", monthly_fee: 999, mau_included: -1,
    overage_rate: 0, workspaces: "unlimited", sla: "99.95%",
    features: ["Unlimited workspaces", "Custom MAU", "All Growth features", "Custom SLA", "Dedicated support", "SSO/SAML", "Audit logs (unlimited)"],
  },
];
